### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by CodionCA** [wolf109909/DrunkDeer-AnalogAdapter#2]
The CPU usage is a tad higher than I expected. I totally get that this might be because the program is polling frequently for accuracy.

I understand if it's a bit tricky to fix, but any insights or updates on this would be super appreciated. Right now, this won't work well with my particular use case.

I can provide more info if needed.

![image](https://github.com/wolf109909/DrunkDeer-AnalogAdapter/assets/61989733/7a1e82cc-32f3-4110-ac85-482be798b0fa)

**Comment by wolf109909** [comment]
I will issue a fix to this problem soon. If things goes well, the internal input polling interval will be exposed to config file.

**Comment by wolf109909** [comment]
This is caused by hid_read operating at non-blocking mode, while in a busy loop. the polling operation itself isn't really heavy on CPU. Still I exposed the setting to config just to make sure everyone is happy.
