### ISSUE TITLE
Deadzone Linearity Fix

### ISSUE THREAD

**Issue by XenoQuaza** [wolf109909/DrunkDeer-AnalogAdapter#4]
With the current implementation of dead zones, changing dead zones only effects a cut off point, above or below which it applies the fixed maximum value. What this means, is that if you have a dead zone of, lets say 5, as you press down on the key, the value would jump straight from 0.0 to 5.01 as you pass it. This jump is a bit less then ideal for stuff like racing games, one of the main uses of analog keyboards. This could be fixed via replacing the following code
![image](https://github.com/user-attachments/assets/529bab94-3b41-44dd-aa88-e41db3a9beb3)
with
![image](https://github.com/user-attachments/assets/ea727355-f877-4f5c-bae5-9fb6f9d7da6e)

**Comment by wolf109909** [comment]
You're right. are you willing to make a pr for this change?

**Comment by XenoQuaza** [comment]
Sure, gimme just a second to actually test this some more before I do though.

**Comment by wolf109909** [comment]
> Sure, gimme just a second to actually test this some more before I do though.

All good, thanks for the contrib!

**Comment by wolf109909** [comment]
fixed by #5
